config/routes.rb
Rails.application.routes.draw do

  resources :cuisine_types

  get 'signin' => "sessions#new"

  resource :session

  get "signup" => "users#new"
  resources :users

  root "trucks#index"
  # get "trucks" => "trucks#index"
  # get "trucks/:id" => "trucks#show", as: "truck"
  # get "trucks/:id/edit" => "trucks#edit", as: "edit_truck"
  # patch "trucks/:id" => "trucks#update"

  resources :trucks do
  	resources :reviews
    resources :follows
  end
end

app/models/truck.rb
class Truck < ActiveRecord::Base
  extend FriendlyId
  friendly_id :name, use: :slugged

  has_many :reviews, dependent: :destroy
  has_many :follows, dependent: :destroy
  # go through the follows association and get users, but call them fans
  has_many :fans, through: :follows, source: :user
  has_many :categorizations, dependent: :destroy
  has_many :cuisine_types, through: :categorizations
  has_attached_file :image

  geocoded_by :address
  after_validation :geocode,
  :if => lambda{ |obj| obj.address_changed? }


  validates_attachment :image,
    :content_type => { :content_type => ['image/jpeg','image/png'] },
    :size => { :less_than => 1.megabyte }
  PAYMENT_OPTIONS = ["Cash, Credit, Interac, PayPal"]

  scope :recent, -> { where('updated_at < ?', Time.now).order('updated_at desc') } 
  scope :popular, -> { all.sort { |a, b| b.fans.count <=> a.fans.count } }

  def display_reviews
    reviews.order("created_at desc").limit(5)
  end
end

app/controllers/trucks_controller.rb
class TrucksController < ApplicationController
	before_action :require_signin, except: [:index, :show]
	before_action :require_admin, except: [:index, :show]

	def index
		if params[:search].present?
			@trucks = Truck.near(params[:search])
		else
			@trucks = Truck.recent
		end
		@hash = Gmaps4rails.build_markers(@trucks) do |truck, marker|
		  marker.lat truck.latitude
		  marker.lng truck.longitude
		  marker.infowindow truck.name
		  marker.picture({
		      "url" => "https://upload.wikimedia.org/wikipedia/commons/0/0a/Map_marker_icon_%E2%80%93_Nicolas_Mollet_%E2%80%93_Truck_%E2%80%93_Transportation_%E2%80%93_Default.png",
		      "width" =>  36,
		      "height" => 36})
		  marker.json({ title: truck.name })
		end
	end

	def show
		@truck = Truck.friendly.find(params[:id])
		@review = Review.new
		@reviews = @truck.display_reviews
		@fans = @truck.fans
		@cuisine_types = @truck.cuisine_types

		if current_user
			@current_fan = current_user.follows.find_by(truck_id: @truck.id)
		end
	end

	def edit
		@truck = Truck.friendly.find(params[:id])
	end

	def update
		@truck = Truck.friendly.find(params[:id])
		if @truck.update(truck_params)
			flash[:notice] = "Event successfully updated."
			redirect_to @truck
		else
			render :edit
		end
	end

	def new
		@truck = Truck.new
	end

	def create
		@truck = Truck.new(truck_params)
		if @truck.save
			redirect_to @truck
		else
			render :new
		end
	end

	def destroy
		@truck = Truck.friendly.find(params[:id])
		@truck.destroy
		redirect_to trucks_url
	end

	private

	def truck_params
		params.require(:truck).permit(:name, :cuisine_type, :address, :longitude, :latitude, :payment_options, :description, :price_range, :image, cuisine_type_ids: [])
	end
end

app/helpers/trucks_helper.rb
module TrucksHelper
	def address_state(truck)
		if truck.address.blank?
			content_tag(:p, "Not Updated.")
		else
			truck.address
		end
	end

	def address_status(truck)
		if truck.address.blank?
			content_tag(:p, "Let's put something amazing here!")
		else
			render 'trucks/address'
		end
	end

	def image_for(truck)
		if truck.image.exists?
			image_tag truck.image.url
		else
			image_tag 'placeholder.jpeg'
		end
	end
end

app/views/trucks/_address.html.erb
  <p>
      <%= @truck.address %>
  </p>

  <%= image_tag "http://maps.google.com/maps/api/staticmap?size=450x300&sensor=false&zoom=16&markers=#{@truck.latitude}%2C#{@truck.longitude}" %>

  <h3>Longitude and Latitude</h3>
  <p>
      Longitude, Latitude: <%= @truck.longitude %>,
      <%= @truck.latitude %>
  </p>
  <h3>Updated:</h3>
  <p>
    <%= time_ago_in_words(@truck.updated_at) %> ago.
  </p>

    <h3><strong>Nearby Eateries</strong></h3>
      <ul>
        <% for truck in @truck.nearbys(10) %>
            <li><%= link_to options = truck.name, truck %> <%= truck.address %> (<%= truck.distance.round(2) %> kms)</li>
        <% end %>
      </ul>

app/views/trucks/_form.html.erb
<%= form_for(@truck) do |f| %>
<%= render 'shared/errors', object: @truck %>
	<p>
		<%= f.label :name %>
		<%= f.text_field :name, autofocus: true %>
	</p>
<!-- 	<p>
		<%#= f.label :cuisine_type %>
		<%#= f.text_field :cuisine_type %>
	</p> -->
	<p>
		<%= f.label :address %>
		<%= f.text_field :address %>
	</p>
	<p>
		<%= f.label :description %>
		<%= f.text_area :description %>
	</p>
	<p>
		<%= f.label :price_range %>
		<%= f.text_field :price_range %>
	</p>

	<p class="required stars">
	  <%= f.label :payment_options %>
	  <%= f.select :payment_options, [ 'Cash', 'Credit', 'Interac', 'PayPal', 'Cash & Credit', 'Cash & Interac', 'Cash & PayPal', 'Cash, Credit & Interac','Cash, Credit, Interac & PayPal', 'Cash, Interac, & PayPal' ], :prompt => 'Select One' %>
	</p>
<!-- 	<p>
		<%#= f.label :longitude %>
		<%#= f.number_field :longitude %>
	</p>
	<p>
		<%#= f.label :latitude %>
		<%#= f.number_field :latitude %>
	</p> -->
	<p>
		<%= f.label :image %>
		<%= f.file_field :image %>
	</p>
	<p>
		<%= image_for(@truck) %>
	</p>
	<p>
		<!-- (1. the array in truck model holding cuisine type ids, 2. Model call to cuisine types, 3. Value of the checkbox from Cuisine_type 4. Label of checkbox is CuisineType name ) -->
		<%= f.collection_check_boxes(:cuisine_type_ids,CuisineType.all,:id,:name) %>
	</p>
	<p>
		<%= f.submit %>
		<%= link_to "Cancel", trucks_path %>
	</p>
<% end %>

app/views/trucks/edit.html.erb
<h1>Editing <%= @truck.name %></h1>

<%= render 'form' %>

app/views/trucks/index.html.erb
<script src="//maps.google.com/maps/api/js?v=3.13&amp;sensor=false&amp;libraries=geometry" type="text/javascript"></script>
<script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js' type='text/javascript'></script>
<script src='//google-maps-utility-library-v3.googlecode.com/svn/trunk/richmarker/src/richmarker-compiled.js' type='text/javascript'></script>

	<% if current_user_admin? %>
		<%= link_to "New Truck", new_truck_path %>
	<% end %>

	<div id="map-canvas"></div>
	<div class="container-fluid" id="main">
	  <div class="row">
	  	<div class="col-xs-12" id="left">
		<h1><%= pluralize(@trucks.size, 'Truck') %> <% pluralize(@trucks.size, 'is') %> in Hamilton.</h1>

	      <h2>Where is my food truck?</h2>

			<div style='width: 800px;'>
			  <div id="map" style='width: 800px; height: 400px;'></div>
			</div>
			<% @trucks.each do |truck| %>
	      <!-- item list -->
				<article class="trucks">
					<header>
						<%= link_to image_for(truck), truck %>
						<div class="">
	       				 <div class=""><h3><%= link_to truck.name, truck %></h3></div>
	      				</div>
					</header>

					<h3>Payment and Pricing:</h3>
						<%= truck.payment_options %><br>
						
						<%= truck.price_range %>
					<h3>Location:</h3>
					<%= truck.address %>
					(Location last updated <%= time_ago_in_words(truck.updated_at) %> ago.)
					<div class="query">
						<i>Is this location corrent?<i>
						<%= link_to "Enter correct address", truck %>
					</div>
						
						<h3><%= Random.rand(0..2.0).round(2) %> kms</h3>
					<hr>
				</article>
			<% end %>

	      <!-- /item list -->

	    </div>

	  </div>
	</div>
	<script type="text/javascript">
	handler = Gmaps.build('Google');
	handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
	  markers = handler.addMarkers(<%=raw @hash.to_json %>)
	  handler.bounds.extendWith(markers);
	  handler.fitMapToBounds();
	});
	</script>
	<!-- end template -->

app/views/trucks/new.html.erb
<h1>New Truck</h1>

<%= render 'form' %>

app/views/trucks/show.html.erb
<% title(@truck.name) %>
<article>
  <header>
    <%= image_for(@truck) %>
    <h1><%= @truck.name %></h1>
  </header>
  
  <h4>Price Range</h3>
  <p>
    <%= @truck.price_range %>
  </p>
  <h4>Payment Options</h3>
  <p>
    <%= @truck.payment_options %>
  </p>
  <h3>Description</h3>
  <p>
    <%= @truck.description %>
  </p>

  <h3>Current Address</h3>
  <!-- if there's an address, it fetches partial, else it displays a message -->
  <%= address_status(@truck) %>

  <h3><%= link_to pluralize(@truck.reviews.count, "Review"), truck_reviews_path(@truck, @current_user) %></h3>

  <% if current_user %>
    <h4>Add yours below:</h4>
    <%= render 'reviews/form' %>
  <% end %>
  <hr>

  <h3><%= pluralize(@fans.size, "Fan") %></h3>
  <% if current_user %>
    <!-- checks to see if person is already a fan-->
    <% if @current_fan %>
      <!-- since the follows routes are nested in truck routes, you need 2 ids, the truck and the current user -->
      <%= button_to "Unfollow", truck_follow_path(@truck, @current_fan), method: :delete %>
    <% else %>
      <%= button_to "Follow", truck_follows_path(@truck, @current_fan) %>
    <% end %>
  <% end %>

  <% if @fans.any? %>
    <h3><%= pluralize(@fans.size,"Fan") %></h3>
    <ul>
      <% @fans.each do |user| %>
        <li>
          <%= profile_image_for(user, size: 35) %>
          <%= link_to user.name, user %>
        </li>
      <% end %>
    </ul>
  <% end %>
  <hr>
  <ol id="reviews">
    <% @reviews.each do |review| %>
      <li>
        <%= profile_image_for(review.user, size: 35) %>
        by <%= link_to review.user.name, review.user %>
        <span class="review"><%= pluralize(review.stars, 'star') %></span>
        <!-- <span class="user">by <%#= review.name %></span> -->
        <span class="date"><%= time_ago_in_words(review.created_at) %> ago</span>
        <p>
          &quot;<%= review.comment %>&quot;
        </p>
      </li>
    <% end %>
  </ol>

  <% if @truck.reviews.any? %>
    <p>
      Read all <%= link_to pluralize(@truck.reviews.size, "review"),
                      truck_reviews_path(@truck) %>
    </p>
  <% end %>
  <h3>Cuisine Type</h3>
  <ul>
    <% @cuisine_types.each do |cuisine_type| %>
      <li>
        <%= cuisine_type.name %>
      </li>
    <% end %>
  </ul>
</article>

<%= link_to "Write a Review", new_truck_review_path(@truck) %>
<%= link_to "All Trucks", trucks_path %> |
<% if current_user_admin? %>
  <%= link_to "Edit", edit_truck_path %> |
  <%= link_to "Delete", truck_path(@truck), method: :delete, data: { confirm: 'Are you sure?' } %>
<% end %>