config/routes.rb
Rails.application.routes.draw do

  resources :cuisine_types

  get 'signin' => "sessions#new"

  resource :session

  get "signup" => "users#new"
  resources :users

  root "trucks#index"
  # get "trucks" => "trucks#index"
  # get "trucks/:id" => "trucks#show", as: "truck"
  # get "trucks/:id/edit" => "trucks#edit", as: "edit_truck"
  # patch "trucks/:id" => "trucks#update"

  resources :trucks do
  	resources :reviews
    resources :follows
  end
end

app/views/layouts/_footer.html.erb
<footer id="page-footer">
	<p>
		Copyright &copy; 2014 Alan
	</p>
</footer>

app/views/layouts/_header.html.erb
<div class="navbar navbar-custom navbar-fixed-top">
 <div class="navbar-header"><%= link_to "Let's eat something.", trucks_path, class: "navbar-brand" %>
      <a class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
    </div>
    <div class="navbar-collapse collapse">
      <form class="navbar-form">
        <div class="form-group" style="display:inline;">
          <div class="input-group">
            <div class="input-group-btn">

            </div>
            <%= form_tag trucks_path, :method => :get do %>
              <%= text_field_tag :search, params[:search], class: 'form-control', placeholder: 'Enter your location?' %>
            <% end %>

            <%= button_tag 'Find Nearby Trucks', id: 'find-nearby-trucks' %>

          </div>
        </div>
      </form>
    </div>
</div>
        <% if current_user %>
          <%= link_to current_user.name, current_user %> |
          <%= link_to "Account Settings", edit_user_path(current_user) %>
          <%= link_to "Sign Out", session_path, method: :delete, class: 'button' %>
        <% else %>
          <%= link_to 'Sign Up', signup_path, class: 'button' %>
          <%= link_to 'Sign In', signin_path, class: 'button' %>
        <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= page_title %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'layouts/header' %>

<%= flash[:notice] %>

<%= yield %>

<%= render 'layouts/footer' %>

</body>
  <link href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css" rel="stylesheet">
  <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
</html>